### ISSUE TITLE
Watcher close immediately if has error

### ISSUE THREAD

**Issue by maxlibin** [denis-ok/rescript-ssg#17]
Watcher failed to load or exit immediately if there is an error, would expect the watcher to continue to watch for file changes and report the error.

**Comment by denis-ok** [comment]
@maxlibin Thanks for reporting!
I think I've faced this issue. Happens for example when you rename some reason file.
Yeah, we need to catch/handle some kind of errors to avoid the watcher exit.

**Comment by denis-ok** [comment]
@maxlibin 
The issue has been addressed here https://github.com/denis-ok/rescript-ssg/commit/cde6b81b09db11f552b9d0f1ef100fbc82c8c659 (the case when you rename files).

It would be great to know what other actions can trigger exceptions.
