### ISSUE TITLE
Getting error when start rescript-ssg

### ISSUE THREAD

**Issue by maxlibin** [denis-ok/rescript-ssg#24]
I am getting an error while starting rescript-ssg, as I understand `node-loader.` will look for `NodeLoader.bs.js` however `NodeLoader.re` was not build at the start and there will be no `NodeLoader.bs.js` file.

```
❯ make start_rescript_ssg

NODE_OPTIONS=--openssl-legacy-provider \
        /Users/max/workspace/frontend/packages/yep/node_modules/.bin/rescript-ssg ./src/Start.bs.js
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/max/workspace/frontend/node_modules/rescript-ssg/src/NodeLoader.bs.js' imported from /Users/max/workspace/frontend/node_modules/rescript-ssg/src/js/node-loader.mjs
```

**Comment by denis-ok** [comment]
@maxlibin 
We need to compile all files before running rescript-ssg.
In one terminal tab, we need to have `bsb`/`rescript` running in watch mode, after it is compiled we can run `make start_rescript_ssg` in another tab.

Side note:
`NODE_OPTIONS=--openssl-legacy-provider` node option can be removed if you install `rescript-ssg` from the latest commit. It was related to the `md4` hash function.
