### ISSUE TITLE
use string for proxy target if changeOrigin is true

### ISSUE THREAD

**Issue by maxlibin** [denis-ok/rescript-ssg#34]
when using proxy with changeOrigin set to true with `Host(url)` 
the proxy port to object: `<i> [webpack-dev-server] [HPM] Proxy created: /search-api/  -> [object Object]`

instead if should pipe to string, read some issue here https://github.com/http-party/node-http-proxy/issues/1028

also the types for target should also be string or object: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/eefa7b7fce1443e2b6ee5e34d84e142880418208/types/http-proxy/index.d.ts#L134

**Comment by denis-ok** [comment]
@maxlibin 
Can you explain please, what is the exact issue?
Something doesn't work or webpack-dev-server displays `[object Object]` but everything works?

**Comment by maxlibin** [comment]
this cause proxy not to work, basically I have set:

```
    proxy: Some([
      {
        from: "/search-api/",
        to_: {
          target: Host("https://api.xxx.xxx/"),
          pathRewrite: Some({from: "^/search-api/", to_: ""}),
          secure: false,
          changeOrigin: true,
        },
      },
    ]),
```
all other things works, however the api proxy route will not work, here's the log:

```
[Webpack dev server] Path rewrites:  []
<i> [webpack-dev-server] [HPM] Proxy created: /search-api/  -> [object Object]
rescript: [243/467] Webapi__Dom__DomStringMap.cmt9m
resolve './packages/yep/src/Maps.bs.js' in '/Users/max/workspace/yep/frontend'
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/
```
