### ISSUE TITLE
pathRewrite always None and leads to undefined in js

### ISSUE THREAD

**Issue by maxlibin** [denis-ok/rescript-ssg#35]
why pathReview was set to None always which compiled to undefined in js as always

https://github.com/denis-ok/rescript-ssg/blob/main/src/Webpack.re#L425

If I understand correctly pathRewrite should take `pathRewrite` type and map to Js.Dict(string)

I suppose it should be something like this:
```
pathRewrite: proxy.to_.pathRewrite->Belt.Option.map(({from, to_}) =>  Js.Dict.fromList([(from, to_)])),
```

Happy to create PR if make sense.

**Comment by denis-ok** [comment]
Addressed by @maxlibin here, thanks:
https://github.com/denis-ok/rescript-ssg/pull/36
Closing.
