### ISSUE TITLE
Adding scripts tag to footer or allow dark mode

### ISSUE THREAD

**Issue by maxlibin** [denis-ok/rescript-ssg#40]
for example in my case I need to add a dark mode script to get localStorage key and update the body class with pre-rended html, which is also to prevent flashing(if we do it on rendered)

```
(function () {
  try {
    var mode = localStorage.getItem('mode');
    var supportDarkMode =
      window.matchMedia('(prefers-color-scheme: dark)').matches === true;
    if (!mode && supportDarkMode) document.body.classList.add('theme-dark');
    if (!mode) return;
    document.body.classList.add('theme-' + mode);
  } catch (e) {}
})();
```

Either we allow script inject or we could provide a dark mode props to support dark mode.  WDYT?

**Comment by denis-ok** [comment]
@maxlibin

For now as a workaround you can inject this script via React helmet / `script` tag, but you'll need to add a little workaround to make sure that script won't re-run after hydration. A small downside of this approach that this script will be also included to JS bundle.

But if we add a param to rescript-ssg to support direct script injection to HTML, that script won't be a part of the bundle.
Can take a look at this when I have a time.

```js
(function () {
  if (!window.themeScriptRan) {
    window.themeScriptRan = true;
    try {
      var mode = localStorage.getItem('mode');
      var supportDarkMode =
        window.matchMedia('(prefers-color-scheme: dark)').matches === true;
      if (!mode && supportDarkMode) document.body.classList.add('theme-dark');
      if (!mode) return;
      document.body.classList.add('theme-' + mode);
    } catch (e) {}
  }
})();
```

**Comment by denis-ok** [comment]
Sorry, I missed that script should be added to the bottom of a document. :)

**Comment by maxlibin** [comment]
PR merged on https://github.com/denis-ok/rescript-ssg/pull/41

Thanks
